version: "3.7"
services:
  api:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "3000:3000"
    restart: always
    container_name: api
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - REDIS_DB=0
      - MONGO_URL=mongodb://mongo:27017/panel
    depends_on:
      - cache
      - mongo
  mongo:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
        - "27017:27017"
#    command: mongod --auth
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=password
#      - MONGO_INITDB_DATABASE=panel
    volumes:
        - ./mongo-data:/data
  cache:
    image: redis
    container_name: cache
    restart: always
    command: redis-server --requirepass "password"
    ports:
        - "6379:6379"
    volumes:
        - ./redis-data:/data